version: '3'

services:
  transaction-server:
    container_name: transaction-server
    image: nginx:alpine
    volumes:
      - ..:/var/www/html/app
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - '80:80'
    networks:
      - transaction-network
    depends_on:
      - transaction-api

  transaction-api:
    container_name: transaction-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=localhost client_port=9000
    volumes:
      - ..:/var/www/html/app
    networks:
      - transaction-network
    depends_on:
      - transaction-database
      - transaction-redis

  transaction-database:
    container_name: transaction-database
    image: 'mysql/mysql-server:8.0'
    restart: unless-stopped
    tty: true
    environment:
        MYSQL_DATABASE: 'transaction'
        MYSQL_USER: 'transaction'
        MYSQL_PASSWORD: 'k9kb-d08r-f7z3'
        MYSQL_ROOT_PASSWORD: 'k9kb-d08r-f7z3'
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    ports:
        - '3306:3306'
    volumes:
        - transaction-data:/var/lib/mysql
        - ../.docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
        - transaction-network

  transaction-redis:
    container_name: transaction-redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - transaction-network

networks:
  transaction-network:
    driver: bridge

volumes:
  transaction-data:
